## YAML Template.
---

server:
    port: 0
    
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

    client:
        registryFetchIntervalSeconds: 5
